"""Initial database schema

Revision ID: 219d04b5d68f
Revises: 
Create Date: 2026-09-10 11:27:32.162733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219d04b5d68f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corridors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('corridor_code', sa.String(), nullable=False),
    sa.Column('corridor_name', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='entitystatus'), nullable=False),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corridors_corridor_code'), 'corridors', ['corridor_code'], unique=True)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_code', sa.String(), nullable=False),
    sa.Column('plan_type', sa.Enum('WEEKLY', 'MONTHLY', name='planninghorizon'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_summary', sa.JSON(), nullable=True),
    sa.Column('output_summary', sa.JSON(), nullable=True),
    sa.Column('tasks_scheduled', sa.Integer(), nullable=False),
    sa.Column('tasks_deferred', sa.Integer(), nullable=False),
    sa.Column('conflicts_detected', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_run_code'), 'optimization_runs', ['run_code'], unique=True)
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_code', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'UNDER_MAINTENANCE', 'DECOMMISSIONED', name='resourcestatus'), nullable=False),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_resource_code'), 'resources', ['resource_code'], unique=True)
    op.create_table('stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('station_code', sa.String(), nullable=False),
    sa.Column('station_name', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='entitystatus'), nullable=False),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_station_code'), 'stations', ['station_code'], unique=True)
    op.create_table('trains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('train_number', sa.String(), nullable=False),
    sa.Column('train_name', sa.String(), nullable=False),
    sa.Column('train_type', sa.Enum('VANDE_BHARAT', 'SUPERFAST', 'EXPRESS', 'GOODS', 'PASSENGER', name='traintype'), nullable=False),
    sa.Column('priority_tier', sa.Integer(), nullable=False),
    sa.Column('is_goods', sa.Boolean(), nullable=False),
    sa.Column('source_station', sa.String(), nullable=False),
    sa.Column('destination_station', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=True),
    sa.Column('arrival_time', sa.String(), nullable=True),
    sa.Column('days_of_run', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'ACTIVE', 'CANCELLED', 'DIVERTED', name='trainstatus'), nullable=False),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    op.create_table('track_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_code', sa.String(), nullable=False),
    sa.Column('corridor_id', sa.Uuid(), nullable=False),
    sa.Column('from_station_id', sa.Uuid(), nullable=False),
    sa.Column('to_station_id', sa.Uuid(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('track_type', sa.String(), nullable=False),
    sa.Column('electrified', sa.Boolean(), nullable=False),
    sa.Column('max_speed', sa.Integer(), nullable=False),
    sa.Column('traffic_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='trafficlevel'), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='assetcriticality'), nullable=False),
    sa.Column('line_type', sa.String(), nullable=False),
    sa.Column('rail_profile', sa.String(), nullable=False),
    sa.Column('sleeper_type', sa.String(), nullable=False),
    sa.Column('fastening_system', sa.String(), nullable=False),
    sa.Column('ballast_depth_mm', sa.Integer(), nullable=False),
    sa.Column('gauge_mm', sa.Integer(), nullable=False),
    sa.Column('gradient_ratio', sa.String(), nullable=False),
    sa.Column('curvature_degrees', sa.Float(), nullable=False),
    sa.Column('start_km_post', sa.Float(), nullable=False),
    sa.Column('end_km_post', sa.Float(), nullable=False),
    sa.Column('traffic_load_gmt', sa.Float(), nullable=False),
    sa.Column('geo_division', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='entitystatus'), nullable=False),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_sections_corridor_id'), 'track_sections', ['corridor_id'], unique=False)
    op.create_index(op.f('ix_track_sections_from_station_id'), 'track_sections', ['from_station_id'], unique=False)
    op.create_index(op.f('ix_track_sections_section_code'), 'track_sections', ['section_code'], unique=True)
    op.create_index(op.f('ix_track_sections_to_station_id'), 'track_sections', ['to_station_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_code', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('department', sa.Enum('ENGINEERING', 'S_AND_T', 'TRD', name='department'), nullable=False),
    sa.Column('track_section_id', sa.Uuid(), nullable=True),
    sa.Column('location_reference', sa.String(), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='assetcriticality'), nullable=False),
    sa.Column('condition', sa.Enum('GOOD', 'FAIR', 'POOR', 'FAILED', name='assetcondition'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='entitystatus'), nullable=False),
    sa.Column('installation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_track_section_id'), 'assets', ['track_section_id'], unique=False)
    op.create_table('block_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.String(), nullable=False),
    sa.Column('track_section_id', sa.Uuid(), nullable=True),
    sa.Column('plan_type', sa.Enum('WEEKLY', 'MONTHLY', name='planninghorizon'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTING', 'COMPLETED', 'SUPERSEDED', name='blockplanstatus'), nullable=False),
    sa.Column('optimization_run_id', sa.Uuid(), nullable=True),
    sa.Column('total_block_hours', sa.Float(), nullable=True),
    sa.Column('total_blocks', sa.Integer(), nullable=True),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('utilization_pct', sa.Float(), nullable=True),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_plans_optimization_run_id'), 'block_plans', ['optimization_run_id'], unique=False)
    op.create_index(op.f('ix_block_plans_plan_code'), 'block_plans', ['plan_code'], unique=True)
    op.create_index(op.f('ix_block_plans_track_section_id'), 'block_plans', ['track_section_id'], unique=False)
    op.create_table('block_windows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_section_id', sa.Uuid(), nullable=False),
    sa.Column('block_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('traffic_block_allowed', sa.Boolean(), nullable=False),
    sa.Column('power_block_allowed', sa.Boolean(), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESTRICTED', 'EMERGENCY', name='blockavailability'), nullable=False),
    sa.Column('traffic_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='trafficlevel'), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_windows_track_section_id'), 'block_windows', ['track_section_id'], unique=False)
    op.create_table('goods_train_forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_section_id', sa.Uuid(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('expected_train_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_train_forecasts_track_section_id'), 'goods_train_forecasts', ['track_section_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspection_code', sa.String(), nullable=False),
    sa.Column('track_section_id', sa.Uuid(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inspection_mode', sa.String(), nullable=False),
    sa.Column('rail_temperature_celsius', sa.Float(), nullable=True),
    sa.Column('ride_quality_index', sa.Float(), nullable=True),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_inspection_code'), 'inspections', ['inspection_code'], unique=True)
    op.create_index(op.f('ix_inspections_track_section_id'), 'inspections', ['track_section_id'], unique=False)
    op.create_table('train_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('train_id', sa.Uuid(), nullable=False),
    sa.Column('track_section_id', sa.Uuid(), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('scheduled_entry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_exit', sa.DateTime(timezone=True), nullable=False),
    sa.Column('movement_type', sa.Enum('SCHEDULED', 'ACTUAL', 'FORECAST', name='movementtype'), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'ACTIVE', 'CANCELLED', 'DIVERTED', name='trainstatus'), nullable=False),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_movements_track_section_id'), 'train_movements', ['track_section_id'], unique=False)
    op.create_index(op.f('ix_train_movements_train_id'), 'train_movements', ['train_id'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('defect_code', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('inspection_id', sa.Uuid(), nullable=True),
    sa.Column('track_section_id', sa.Uuid(), nullable=True),
    sa.Column('department', sa.Enum('ENGINEERING', 'S_AND_T', 'TRD', name='department'), nullable=False),
    sa.Column('defect_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('safety_impact', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('is_rectified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DEFERRED', name='maintenancestatus'), nullable=False),
    sa.Column('exact_km_post', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_asset_id'), 'defects', ['asset_id'], unique=False)
    op.create_index(op.f('ix_defects_defect_code'), 'defects', ['defect_code'], unique=True)
    op.create_index(op.f('ix_defects_inspection_id'), 'defects', ['inspection_id'], unique=False)
    op.create_index(op.f('ix_defects_track_section_id'), 'defects', ['track_section_id'], unique=False)
    op.create_table('plan_conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('train_movement_id', sa.Uuid(), nullable=True),
    sa.Column('block_window_id', sa.Uuid(), nullable=True),
    sa.Column('conflict_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_window_id'], ['block_windows.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['block_plans.id'], ),
    sa.ForeignKeyConstraint(['train_movement_id'], ['train_movements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_conflicts_block_window_id'), 'plan_conflicts', ['block_window_id'], unique=False)
    op.create_index(op.f('ix_plan_conflicts_plan_id'), 'plan_conflicts', ['plan_id'], unique=False)
    op.create_index(op.f('ix_plan_conflicts_train_movement_id'), 'plan_conflicts', ['train_movement_id'], unique=False)
    op.create_table('plan_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'OVERRIDDEN', name='plandecisiontype'), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('modified_tasks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['block_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_decisions_plan_id'), 'plan_decisions', ['plan_id'], unique=False)
    op.create_table('plan_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['block_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_versions_plan_id'), 'plan_versions', ['plan_id'], unique=False)
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_code', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('defect_id', sa.Uuid(), nullable=True),
    sa.Column('track_section_id', sa.Uuid(), nullable=True),
    sa.Column('department', sa.Enum('ENGINEERING', 'S_AND_T', 'TRD', name='department'), nullable=False),
    sa.Column('issue_description', sa.String(), nullable=False),
    sa.Column('reported_by', sa.String(), nullable=False),
    sa.Column('reported_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='priorityclass'), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='assetcriticality'), nullable=False),
    sa.Column('urgency', sa.Float(), nullable=True),
    sa.Column('safety_impact', sa.String(), nullable=True),
    sa.Column('operational_impact', sa.String(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('required_block_minutes', sa.Integer(), nullable=True),
    sa.Column('traffic_block_required', sa.Boolean(), nullable=False),
    sa.Column('power_block_required', sa.Boolean(), nullable=False),
    sa.Column('requested_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DEFERRED', name='maintenancestatus'), nullable=False),
    sa.Column('assigned_team', sa.String(), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('source_department', sa.String(), nullable=True),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_requests_asset_id'), 'maintenance_requests', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_defect_id'), 'maintenance_requests', ['defect_id'], unique=False)
    op.create_index(op.f('ix_maintenance_requests_request_code'), 'maintenance_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_maintenance_requests_track_section_id'), 'maintenance_requests', ['track_section_id'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('defect_id', sa.Uuid(), nullable=True),
    sa.Column('track_section_id', sa.Uuid(), nullable=True),
    sa.Column('department', sa.Enum('ENGINEERING', 'S_AND_T', 'TRD', name='department'), nullable=False),
    sa.Column('task_type', sa.Enum('TRACK_RENEWAL', 'RAIL_REPLACEMENT', 'SLEEPER_REPLACEMENT', 'BALLAST_CLEANING', 'BALLAST_REPLENISHMENT', 'WELD_REPAIR', 'ROUTINE_MAINTENANCE', 'SIGNAL_MAINTENANCE', 'OHE_MAINTENANCE', 'BRIDGE_INSPECTION', 'EMERGENCY_REPAIR', 'OTHER', name='tasktype'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('required_block_minutes', sa.Integer(), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='assetcriticality'), nullable=False),
    sa.Column('urgency', sa.Float(), nullable=True),
    sa.Column('safety_impact', sa.String(), nullable=True),
    sa.Column('operational_impact', sa.String(), nullable=True),
    sa.Column('required_resources', sa.String(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DEFERRED', name='maintenancestatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['maintenance_requests.id'], ),
    sa.ForeignKeyConstraint(['track_section_id'], ['track_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tasks_asset_id'), 'maintenance_tasks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_defect_id'), 'maintenance_tasks', ['defect_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_request_id'), 'maintenance_tasks', ['request_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_track_section_id'), 'maintenance_tasks', ['track_section_id'], unique=False)
    op.create_table('block_plan_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('block_plan_id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_task_id', sa.Uuid(), nullable=False),
    sa.Column('block_window_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DEFERRED', name='maintenancestatus'), nullable=False),
    sa.Column('assignment_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_plan_id'], ['block_plans.id'], ),
    sa.ForeignKeyConstraint(['block_window_id'], ['block_windows.id'], ),
    sa.ForeignKeyConstraint(['maintenance_task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_plan_tasks_block_plan_id'), 'block_plan_tasks', ['block_plan_id'], unique=False)
    op.create_index(op.f('ix_block_plan_tasks_block_window_id'), 'block_plan_tasks', ['block_window_id'], unique=False)
    op.create_index(op.f('ix_block_plan_tasks_maintenance_task_id'), 'block_plan_tasks', ['maintenance_task_id'], unique=False)
    op.create_table('priority_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_class', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='priorityclass'), nullable=False),
    sa.Column('factor_scores', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priority_results_task_id'), 'priority_results', ['task_id'], unique=False)
    op.create_table('resource_deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('work_order_code', sa.String(), nullable=True),
    sa.Column('runtime_hours', sa.Float(), nullable=True),
    sa.Column('deployment_date', sa.Date(), nullable=False),
    sa.Column('source_type', sa.Enum('SYNTHETIC_SEED', 'SYNTHETIC_GENERATED', 'SIMULATED', 'USER_ENTERED', name='sourcetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_deployments_resource_id'), 'resource_deployments', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_deployments_task_id'), 'resource_deployments', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_deployments_task_id'), table_name='resource_deployments')
    op.drop_index(op.f('ix_resource_deployments_resource_id'), table_name='resource_deployments')
    op.drop_table('resource_deployments')
    op.drop_index(op.f('ix_priority_results_task_id'), table_name='priority_results')
    op.drop_table('priority_results')
    op.drop_index(op.f('ix_block_plan_tasks_maintenance_task_id'), table_name='block_plan_tasks')
    op.drop_index(op.f('ix_block_plan_tasks_block_window_id'), table_name='block_plan_tasks')
    op.drop_index(op.f('ix_block_plan_tasks_block_plan_id'), table_name='block_plan_tasks')
    op.drop_table('block_plan_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_track_section_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_request_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_defect_id'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_asset_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_requests_track_section_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_request_code'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_defect_id'), table_name='maintenance_requests')
    op.drop_index(op.f('ix_maintenance_requests_asset_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_index(op.f('ix_plan_versions_plan_id'), table_name='plan_versions')
    op.drop_table('plan_versions')
    op.drop_index(op.f('ix_plan_decisions_plan_id'), table_name='plan_decisions')
    op.drop_table('plan_decisions')
    op.drop_index(op.f('ix_plan_conflicts_train_movement_id'), table_name='plan_conflicts')
    op.drop_index(op.f('ix_plan_conflicts_plan_id'), table_name='plan_conflicts')
    op.drop_index(op.f('ix_plan_conflicts_block_window_id'), table_name='plan_conflicts')
    op.drop_table('plan_conflicts')
    op.drop_index(op.f('ix_defects_track_section_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_inspection_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_defect_code'), table_name='defects')
    op.drop_index(op.f('ix_defects_asset_id'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_train_movements_train_id'), table_name='train_movements')
    op.drop_index(op.f('ix_train_movements_track_section_id'), table_name='train_movements')
    op.drop_table('train_movements')
    op.drop_index(op.f('ix_inspections_track_section_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspection_code'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_goods_train_forecasts_track_section_id'), table_name='goods_train_forecasts')
    op.drop_table('goods_train_forecasts')
    op.drop_index(op.f('ix_block_windows_track_section_id'), table_name='block_windows')
    op.drop_table('block_windows')
    op.drop_index(op.f('ix_block_plans_track_section_id'), table_name='block_plans')
    op.drop_index(op.f('ix_block_plans_plan_code'), table_name='block_plans')
    op.drop_index(op.f('ix_block_plans_optimization_run_id'), table_name='block_plans')
    op.drop_table('block_plans')
    op.drop_index(op.f('ix_assets_track_section_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_track_sections_to_station_id'), table_name='track_sections')
    op.drop_index(op.f('ix_track_sections_section_code'), table_name='track_sections')
    op.drop_index(op.f('ix_track_sections_from_station_id'), table_name='track_sections')
    op.drop_index(op.f('ix_track_sections_corridor_id'), table_name='track_sections')
    op.drop_table('track_sections')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_stations_station_code'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_resources_resource_code'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_optimization_runs_run_code'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_corridors_corridor_code'), table_name='corridors')
    op.drop_table('corridors')
    # ### end Alembic commands ###
